---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.6.0

platforms:
- name: centos-7.0
  driver_config:
    box: opscode-centos-7.0

suites:
- name: default
  run_list: ['recipe[mysql_yum_repo::default]']
  attributes:
    cloud:
      provider: vagrant
